-- ==============================================================================
-- KURAL LPU & LPU TAMIZHANS — CANONICAL MASTER DATABASE SCHEMA & RLS POLICIES
-- File: supabase/schema_master.sql
-- ==============================================================================
-- This master file consolidates all database tables, columns, indexes, and
-- Row-Level Security (RLS) policies into a single canonical source of truth.
--
-- Security Model:
-- - Zero hardcoded PII/emails.
-- - Admin privileges verified dynamically via SECURITY DEFINER function public.is_admin().
-- - Anonymous/Public users can ONLY read published content and submit forms.
-- - Strict RLS enforced across all tables including team_applications & contact_messages.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 0. ADMINS REGISTRY & SECURITY DEFINER HELPER FUNCTION
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view their own record" ON public.admins;
CREATE POLICY "Admins can view their own record"
ON public.admins FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Secure, cached admin check function (SECURITY DEFINER)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$;

-- Automatically enroll the initial admin (first user in auth.users)
INSERT INTO public.admins (user_id)
SELECT id FROM auth.users
ORDER BY created_at ASC
LIMIT 1
ON CONFLICT (user_id) DO NOTHING;


-- ------------------------------------------------------------------------------
-- 1. SITE_CONTENT TABLE (About, Home, Kural, Gallery text & settings)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.site_content (
  id TEXT PRIMARY KEY,
  content TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read-only access on site_content" ON public.site_content;
DROP POLICY IF EXISTS "Admin only insert on site_content" ON public.site_content;
DROP POLICY IF EXISTS "Admin only update on site_content" ON public.site_content;
DROP POLICY IF EXISTS "Admin only delete on site_content" ON public.site_content;

CREATE POLICY "Public read-only access on site_content"
ON public.site_content FOR SELECT
TO public
USING (true);

CREATE POLICY "Admin only insert on site_content"
ON public.site_content FOR INSERT
TO authenticated
WITH CHECK (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin only update on site_content"
ON public.site_content FOR UPDATE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
)
WITH CHECK (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin only delete on site_content"
ON public.site_content FOR DELETE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);


-- ------------------------------------------------------------------------------
-- 2. MOMENTS TABLE (Events, Celebrations, Highlights & Media Archive)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.moments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  tag TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT NOT NULL,
  location TEXT,
  organized_by TEXT,
  about TEXT,
  highlights TEXT,
  activities TEXT,
  gallery_images JSONB DEFAULT '[]'::jsonb,
  is_featured BOOLEAN DEFAULT false,
  featured_order INTEGER DEFAULT 0,
  is_upcoming BOOLEAN DEFAULT false
);

-- Ensure all featured columns and indexes exist
ALTER TABLE public.moments 
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS featured_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_upcoming BOOLEAN DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_moments_featured 
ON public.moments(is_featured, featured_order, is_upcoming);

ALTER TABLE public.moments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read-only access on moments" ON public.moments;
DROP POLICY IF EXISTS "Admin only insert on moments" ON public.moments;
DROP POLICY IF EXISTS "Admin only update on moments" ON public.moments;
DROP POLICY IF EXISTS "Admin only delete on moments" ON public.moments;

CREATE POLICY "Public read-only access on moments"
ON public.moments FOR SELECT
TO public
USING (true);

CREATE POLICY "Admin only insert on moments"
ON public.moments FOR INSERT
TO authenticated
WITH CHECK (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin only update on moments"
ON public.moments FOR UPDATE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
)
WITH CHECK (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin only delete on moments"
ON public.moments FOR DELETE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);


-- ------------------------------------------------------------------------------
-- 3. TEAM_MEMBERS TABLE (Team Profiles & Department Leadership)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  department TEXT NOT NULL,
  batch TEXT NOT NULL,
  image_url TEXT NOT NULL,
  bio TEXT,
  responsibilities TEXT,
  skills TEXT,
  instagram TEXT,
  linkedin TEXT,
  github TEXT,
  email TEXT,
  order_num INTEGER DEFAULT 0
);

ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public read-only access on team_members" ON public.team_members;
DROP POLICY IF EXISTS "Admin only insert on team_members" ON public.team_members;
DROP POLICY IF EXISTS "Admin only update on team_members" ON public.team_members;
DROP POLICY IF EXISTS "Admin only delete on team_members" ON public.team_members;

CREATE POLICY "Public read-only access on team_members"
ON public.team_members FOR SELECT
TO public
USING (true);

CREATE POLICY "Admin only insert on team_members"
ON public.team_members FOR INSERT
TO authenticated
WITH CHECK (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin only update on team_members"
ON public.team_members FOR UPDATE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
)
WITH CHECK (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin only delete on team_members"
ON public.team_members FOR DELETE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);


-- ------------------------------------------------------------------------------
-- 4. CONTACT_MESSAGES TABLE (Public Inquiries)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can insert contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Admin can read contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Admin can delete contact messages" ON public.contact_messages;

-- Public can submit messages
CREATE POLICY "Public can insert contact messages"
ON public.contact_messages FOR INSERT
TO public
WITH CHECK (true);

-- Only authenticated verified admins can view and delete messages
CREATE POLICY "Admin can read contact messages"
ON public.contact_messages FOR SELECT
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admin can delete contact messages"
ON public.contact_messages FOR DELETE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);


-- ------------------------------------------------------------------------------
-- 5. TEAM_APPLICATIONS TABLE (Core Team Recruits & Submissions)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.team_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  department TEXT NOT NULL,
  batch TEXT NOT NULL,
  interest_area TEXT NOT NULL,
  message TEXT
);

ALTER TABLE public.team_applications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can apply" ON public.team_applications;
DROP POLICY IF EXISTS "Admins can read applications" ON public.team_applications;
DROP POLICY IF EXISTS "Admins can delete applications" ON public.team_applications;

-- Public applicants can INSERT
CREATE POLICY "Anyone can apply"
ON public.team_applications FOR INSERT
TO public
WITH CHECK (true);

-- STRICT ADMIN-ONLY ACCESS (Fixed: uses public.is_admin() instead of loose authenticated check)
CREATE POLICY "Admins can read applications"
ON public.team_applications FOR SELECT
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);

CREATE POLICY "Admins can delete applications"
ON public.team_applications FOR DELETE
TO authenticated
USING (
  auth.role() = 'authenticated' AND public.is_admin()
);


-- ------------------------------------------------------------------------------
-- 6. STORAGE OBJECTS (Moments, Covers & Profile Photos)
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Public read-only access on storage moments" ON storage.objects;
DROP POLICY IF EXISTS "Admin only insert on storage moments" ON storage.objects;
DROP POLICY IF EXISTS "Admin only update on storage moments" ON storage.objects;
DROP POLICY IF EXISTS "Admin only delete on storage moments" ON storage.objects;

CREATE POLICY "Public read-only access on storage moments"
ON storage.objects FOR SELECT
TO public
USING (bucket_id = 'moments');

CREATE POLICY "Admin only insert on storage moments"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'moments' 
  AND auth.role() = 'authenticated' 
  AND public.is_admin()
);

CREATE POLICY "Admin only update on storage moments"
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'moments' 
  AND auth.role() = 'authenticated' 
  AND public.is_admin()
);

CREATE POLICY "Admin only delete on storage moments"
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'moments' 
  AND auth.role() = 'authenticated' 
  AND public.is_admin()
);
